.TH chocolatechip 1
.SH NAME
chocolatechip \- A CHIP-8 Emulator written in C99 by Prathik Gowda
.SH SYNOPSIS
.B chocolatechip
.RB [\-d]
.IR romfile
.SH DESCRIPTION
.B chocolatechip
provides a virtual machine to run ROMs originally written for the CHIP-8. To run
a rom with chocolatechip, pass the rom filename as a command line argument.
.SH OPTIONS
.TP
.BR \-d
enables debugging information
